2023-03-10 17:01:29,226 ERROR: Exception on /login [GET] [in /home/yagopeixinho/.local/lib/python3.10/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/yagopeixinho/Desktop/Local/Personal/Github/Repositories/microblog/app/routes.py", line 47, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/yagopeixinho/Desktop/Local/Personal/Github/Repositories/microblog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/yagopeixinho/Desktop/Local/Personal/Github/Repositories/microblog/app/templates/base.html", line 35, in top-level template code
    {% block content %}{% endblock %}
  File "/home/yagopeixinho/Desktop/Local/Personal/Github/Repositories/microblog/app/templates/login.html", line 28, in block 'content'
    <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
2023-03-10 17:02:00,925 ERROR: Exception on /login [GET] [in /home/yagopeixinho/.local/lib/python3.10/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/yagopeixinho/Desktop/Local/Personal/Github/Repositories/microblog/app/routes.py", line 47, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/yagopeixinho/Desktop/Local/Personal/Github/Repositories/microblog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/yagopeixinho/Desktop/Local/Personal/Github/Repositories/microblog/app/templates/base.html", line 35, in top-level template code
    {% block content %}{% endblock %}
  File "/home/yagopeixinho/Desktop/Local/Personal/Github/Repositories/microblog/app/templates/login.html", line 28, in block 'content'
    <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
2023-03-10 17:02:22,079 ERROR: Exception on /login [GET] [in /home/yagopeixinho/.local/lib/python3.10/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/yagopeixinho/Desktop/Local/Personal/Github/Repositories/microblog/app/routes.py", line 47, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/yagopeixinho/Desktop/Local/Personal/Github/Repositories/microblog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/yagopeixinho/Desktop/Local/Personal/Github/Repositories/microblog/app/templates/base.html", line 35, in top-level template code
    {% block content %}{% endblock %}
  File "/home/yagopeixinho/Desktop/Local/Personal/Github/Repositories/microblog/app/templates/login.html", line 28, in block 'content'
    <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/yagopeixinho/.local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
